export default {
    products: [
        {
            _id: '1',
            name: 'Full Zip ',
            category: 'Shirts',
            image: 'images/product-1.jpg',
            price: 60,
            brand: 'adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Nomaland ',
            category: 'Shir',
            image: 'images/product-2.jpg',
            price: 70,
            brand: 'adidas',
            rating: 5,
            numReviews: 40,
            countInStock: 20,
        },
        {
            _id: '3',
            name: 'haft Zip ',
            category: 'shot',
            image: 'images/product-3.jpg',
            price: 600,
            brand: 'none',
            rating: 4.5,
            numReviews: 80,
            countInStock: 16,
        },
        {
            _id: '4',
            name: 'Full Zip ',
            category: 'Shirts',
            image: 'images/product-4.jpg',
            price: 20,
            brand: 'polo',
            rating: 4.5,
            numReviews: 210,
            countInStock: 1,
        },
        {
            _id: '5',
            name: 'Full hip ',
            category: 'Shirts',
            image: 'images/product-5.jpg',
            price: 80,
            brand: 'puma',
            rating: 4,
            numReviews: 100,
            countInStock: 15,
        },
        {
            _id: '6',
            name: 'Full Zip Name ',
            category: 'Jean',
            image: 'images/product-6.jpg',
            price: 60,
            brand: 'adidas',
            rating: 5,
            numReviews: 18,
            countInStock: 8,
        },
    ],
};